const Mock = require('mockjs');

const data = function () {
    return Mock.mock({
        code: 0,
        data: {
            count: 0,
            list: [
                {
                    id: '100357',
                    portrait: 'http://192.168.10.214/img/9fd23cd0-9a1c-49d1-8c9d-ae1ab2f768ad.png',
                    doctorType: '1',
                    username: '18516696167',
                    realname: '姚怀广',
                    titleType: '副主任医师',
                    hospitalId: '4535',
                    hospitalName: '塘桥社区卫生服务中心',
                    hospitalLevel: '1',
                    departmentName: '全科医生',
                    unReadNum: 0,
                    lastChatTimestamp: 0,
                    filterScore: 0,
                    doctorDetailRoute: 'router://doctorHybridWebView?url=/matrix/doctor.html#/home?doctorId=100357',
                    leapfrog: false,
                    portraitBgColorFrom: '#eb5c8c',
                    portraitBgColorTo: '#d43e72',
                    applyId: '101416',
                    status: '0',
                    inCooperativeHospital: false
                },
                {
                    id: '183225868',
                    portrait: 'http://192.168.10.214/img/29c9f5ae-b2d7-4a65-a1e4-4d349b23d3f1.png',
                    doctorType: '3',
                    username: '18801767713',
                    realname: '琼琼',
                    titleType: '护师',
                    hospitalId: '4523',
                    hospitalName: '米喜云医院',
                    hospitalLevel: '1',
                    departmentName: '护士',
                    unReadNum: 0,
                    lastChatTimestamp: 0,
                    filterScore: 0,
                    doctorDetailRoute: 'router://doctorHybridWebView?url=/matrix/doctor.html#/home?doctorId=183225868',
                    leapfrog: false,
                    portraitBgColorFrom: '#eb5c8c',
                    portraitBgColorTo: '#d43e72',
                    applyId: '101379',
                    status: '1',
                    inCooperativeHospital: false
                },
                {
                    id: '100696',
                    portrait: 'http://192.168.10.214/img/61a1dc2c-9e12-4067-b1eb-23e2c30d5d3f.jpg',
                    doctorType: '1',
                    username: '13122193641',
                    realname: '没事',
                    titleType: '主任医师',
                    hospitalId: '1258',
                    hospitalName: '四平社区卫生服务中心',
                    hospitalLevel: '1',
                    departmentName: '全科医生',
                    unReadNum: 0,
                    lastChatTimestamp: 0,
                    filterScore: 0,
                    doctorDetailRoute: 'router://doctorHybridWebView?url=/matrix/doctor.html#/home?doctorId=100696',
                    leapfrog: false,
                    portraitBgColorFrom: '#eb5c8c',
                    portraitBgColorTo: '#d43e72',
                    applyId: '101374',
                    status: '2',
                    inCooperativeHospital: false
                },
                {
                    id: '100696',
                    portrait: 'http://192.168.10.214/img/61a1dc2c-9e12-4067-b1eb-23e2c30d5d3f.jpg',
                    doctorType: '1',
                    username: '13122193641',
                    realname: '没事',
                    titleType: '主任医师',
                    hospitalId: '1258',
                    hospitalName: '四平社区卫生服务中心',
                    hospitalLevel: '1',
                    departmentName: '全科医生',
                    unReadNum: 0,
                    lastChatTimestamp: 0,
                    filterScore: 0,
                    doctorDetailRoute: 'router://doctorHybridWebView?url=/matrix/doctor.html#/home?doctorId=100696',
                    leapfrog: false,
                    portraitBgColorFrom: '#eb5c8c',
                    portraitBgColorTo: '#d43e72',
                    applyId: '101375',
                    status: '1',
                    inCooperativeHospital: false
                },
                {
                    id: '100696',
                    portrait: 'http://192.168.10.214/img/61a1dc2c-9e12-4067-b1eb-23e2c30d5d3f.jpg',
                    doctorType: '1',
                    username: '13122193641',
                    realname: '没事',
                    titleType: '主任医师',
                    hospitalId: '1258',
                    hospitalName: '四平社区卫生服务中心',
                    hospitalLevel: '1',
                    departmentName: '全科医生',
                    unReadNum: 0,
                    lastChatTimestamp: 0,
                    filterScore: 0,
                    doctorDetailRoute: 'router://doctorHybridWebView?url=/matrix/doctor.html#/home?doctorId=100696',
                    leapfrog: false,
                    portraitBgColorFrom: '#eb5c8c',
                    portraitBgColorTo: '#d43e72',
                    applyId: '101376',
                    status: '1',
                    inCooperativeHospital: false
                },
                {
                    id: '100696',
                    portrait: 'http://192.168.10.214/img/61a1dc2c-9e12-4067-b1eb-23e2c30d5d3f.jpg',
                    doctorType: '1',
                    username: '13122193641',
                    realname: '没事',
                    titleType: '主任医师',
                    hospitalId: '1258',
                    hospitalName: '四平社区卫生服务中心',
                    hospitalLevel: '1',
                    departmentName: '全科医生',
                    unReadNum: 0,
                    lastChatTimestamp: 0,
                    filterScore: 0,
                    doctorDetailRoute: 'router://doctorHybridWebView?url=/matrix/doctor.html#/home?doctorId=100696',
                    leapfrog: false,
                    portraitBgColorFrom: '#eb5c8c',
                    portraitBgColorTo: '#d43e72',
                    applyId: '101372',
                    status: '1',
                    inCooperativeHospital: false
                },
                {
                    id: '100696',
                    portrait: 'http://192.168.10.214/img/61a1dc2c-9e12-4067-b1eb-23e2c30d5d3f.jpg',
                    doctorType: '1',
                    username: '13122193641',
                    realname: '没事',
                    titleType: '主任医师',
                    hospitalId: '1258',
                    hospitalName: '四平社区卫生服务中心',
                    hospitalLevel: '1',
                    departmentName: '全科医生',
                    unReadNum: 0,
                    lastChatTimestamp: 0,
                    filterScore: 0,
                    doctorDetailRoute: 'router://doctorHybridWebView?url=/matrix/doctor.html#/home?doctorId=100696',
                    leapfrog: false,
                    portraitBgColorFrom: '#eb5c8c',
                    portraitBgColorTo: '#d43e72',
                    applyId: '101373',
                    status: '1',
                    inCooperativeHospital: false
                },
                {
                    id: '100696',
                    portrait: 'http://192.168.10.214/img/61a1dc2c-9e12-4067-b1eb-23e2c30d5d3f.jpg',
                    doctorType: '1',
                    username: '13122193641',
                    realname: '没事',
                    titleType: '主任医师',
                    hospitalId: '1258',
                    hospitalName: '四平社区卫生服务中心',
                    hospitalLevel: '1',
                    departmentName: '全科医生',
                    unReadNum: 0,
                    lastChatTimestamp: 0,
                    filterScore: 0,
                    doctorDetailRoute: 'router://doctorHybridWebView?url=/matrix/doctor.html#/home?doctorId=100696',
                    leapfrog: false,
                    portraitBgColorFrom: '#eb5c8c',
                    portraitBgColorTo: '#d43e72',
                    applyId: '101371',
                    status: '1',
                    inCooperativeHospital: false
                },
                {
                    id: '100696',
                    portrait: 'http://192.168.10.214/img/61a1dc2c-9e12-4067-b1eb-23e2c30d5d3f.jpg',
                    doctorType: '1',
                    username: '13122193641',
                    realname: '没事',
                    titleType: '主任医师',
                    hospitalId: '1258',
                    hospitalName: '四平社区卫生服务中心',
                    hospitalLevel: '1',
                    departmentName: '全科医生',
                    unReadNum: 0,
                    lastChatTimestamp: 0,
                    filterScore: 0,
                    doctorDetailRoute: 'router://doctorHybridWebView?url=/matrix/doctor.html#/home?doctorId=100696',
                    leapfrog: false,
                    portraitBgColorFrom: '#eb5c8c',
                    portraitBgColorTo: '#d43e72',
                    applyId: '101370',
                    status: '1',
                    inCooperativeHospital: false
                }
            ]
        }
    });
};
module.exports = data;
